Creating a DataFrames

In [36]:
import numpy as np
import pandas as pd

In [37]:
data = {
    'Name': ['Mayank Joshi', 'Mamta Rawat', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [38]:
df

           Name  Age      City  Salary
0  Mayank Joshi   28  New York   65000
1   Mamta Rawat   34     Paris   70000
2         Peter   29    Berlin   62000
3         Linda   42    London   85000

In [39]:
data_list = [
    ['Mayank Joshi', 20, 'New York', 165000],
    ['Mamta Rawat', 19, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
column = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list,columns= column)
df2

           Name  Age      City  Salary
0  Mayank Joshi   20  New York  165000
1   Mamta Rawat   19     Paris   70000
2         Peter   29    Berlin   62000
3         Linda   42    London   85000

Selection And Indexing of columns

In [40]:
df2[['Name','City']]

           Name      City
0  Mayank Joshi  New York
1   Mamta Rawat     Paris
2         Peter    Berlin
3         Linda    London

Creating a new column

In [41]:
df2["Degisnation"] = [" AI & ML Software Engineer","AI & ML Engineer","Doctor","Engineer"]

In [42]:
df2

           Name  Age      City  Salary                 Degisnation
0  Mayank Joshi   20  New York  165000   AI & ML Software Engineer
1   Mamta Rawat   19     Paris   70000            AI & ML Engineer
2         Peter   29    Berlin   62000                      Doctor
3         Linda   42    London   85000                    Engineer

In [43]:
df2.drop("City",axis = 1,inplace = True )

In [44]:
df2.drop(["Salary"],axis = 1)

           Name  Age                 Degisnation
0  Mayank Joshi   20   AI & ML Software Engineer
1   Mamta Rawat   19            AI & ML Engineer
2         Peter   29                      Doctor
3         Linda   42                    Engineer

In [45]:
df2

           Name  Age  Salary                 Degisnation
0  Mayank Joshi   20  165000   AI & ML Software Engineer
1   Mamta Rawat   19   70000            AI & ML Engineer
2         Peter   29   62000                      Doctor
3         Linda   42   85000                    Engineer

In [48]:
df2.drop([2,3],axis=0)

           Name  Age  Salary                 Degisnation
0  Mayank Joshi   20  165000   AI & ML Software Engineer
1   Mamta Rawat   19   70000            AI & ML Engineer

Selecting Row

In [49]:
df2.loc[0]

Name                         Mayank Joshi
Age                                    20
Salary                             165000
Degisnation     AI & ML Software Engineer
Name: 0, dtype: object

In [51]:
df2.loc[[0,1]]

           Name  Age  Salary                 Degisnation
0  Mayank Joshi   20  165000   AI & ML Software Engineer
1   Mamta Rawat   19   70000            AI & ML Engineer

In [52]:
df2.iloc[[0,1]]

           Name  Age  Salary                 Degisnation
0  Mayank Joshi   20  165000   AI & ML Software Engineer
1   Mamta Rawat   19   70000            AI & ML Engineer

Selecting Subsets of rows and cloumns

In [53]:
df2

           Name  Age  Salary                 Degisnation
0  Mayank Joshi   20  165000   AI & ML Software Engineer
1   Mamta Rawat   19   70000            AI & ML Engineer
2         Peter   29   62000                      Doctor
3         Linda   42   85000                    Engineer

In [54]:
df2.loc[[0,1]][['Salary','Degisnation']]

   Salary                 Degisnation
0  165000   AI & ML Software Engineer
1   70000            AI & ML Engineer