Creating a DataFrames

In [174]:
import numpy as np
import pandas as pd

In [175]:
data = {
    'Name': ['Mayank Joshi', 'Mamta Rawat', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [176]:
df

           Name  Age      City  Salary
0  Mayank Joshi   28  New York   65000
1   Mamta Rawat   34     Paris   70000
2         Peter   29    Berlin   62000
3         Linda   42    London   85000

In [177]:
data_list = [
    ['Mayank Joshi', 20, 'New York', 165000],
    ['Mamta Rawat', 19, 'Paris', 160000],
    ['Peter', 18, 'Berlin', 62000],
    ['Linda', 17, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
column = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list,columns= column)
df2

           Name  Age      City  Salary
0  Mayank Joshi   20  New York  165000
1   Mamta Rawat   19     Paris  160000
2         Peter   18    Berlin   62000
3         Linda   17    London   85000

Selection And Indexing of columns

In [178]:
df2[['Name','City']]

           Name      City
0  Mayank Joshi  New York
1   Mamta Rawat     Paris
2         Peter    Berlin
3         Linda    London

Creating a new column

In [179]:
df2["Job"] = ["Engineer","Engineer","Doctor","Plumber"]

In [180]:
df2

           Name  Age      City  Salary       Job
0  Mayank Joshi   20  New York  165000  Engineer
1   Mamta Rawat   19     Paris  160000  Engineer
2         Peter   18    Berlin   62000    Doctor
3         Linda   17    London   85000   Plumber

In [181]:
df2.drop("City",axis = 1,inplace = True )

In [182]:
df2.drop(["Salary"],axis = 1)

           Name  Age       Job
0  Mayank Joshi   20  Engineer
1   Mamta Rawat   19  Engineer
2         Peter   18    Doctor
3         Linda   17   Plumber

In [183]:
df2

           Name  Age  Salary       Job
0  Mayank Joshi   20  165000  Engineer
1   Mamta Rawat   19  160000  Engineer
2         Peter   18   62000    Doctor
3         Linda   17   85000   Plumber

In [184]:
df2.drop([2,3],axis=0)

           Name  Age  Salary       Job
0  Mayank Joshi   20  165000  Engineer
1   Mamta Rawat   19  160000  Engineer

Selecting Row

In [185]:
df2.loc[0]

Name      Mayank Joshi
Age                 20
Salary          165000
Job           Engineer
Name: 0, dtype: object

In [186]:
df2.loc[[0,1]]

           Name  Age  Salary       Job
0  Mayank Joshi   20  165000  Engineer
1   Mamta Rawat   19  160000  Engineer

In [187]:
df2.iloc[[0,1]]

           Name  Age  Salary       Job
0  Mayank Joshi   20  165000  Engineer
1   Mamta Rawat   19  160000  Engineer

Selecting Subsets of rows and cloumns

In [188]:
df2

           Name  Age  Salary       Job
0  Mayank Joshi   20  165000  Engineer
1   Mamta Rawat   19  160000  Engineer
2         Peter   18   62000    Doctor
3         Linda   17   85000   Plumber

In [189]:
df2.loc[[0,1]][['Salary','Degisnation']]

KeyError: "['Degisnation'] not in index"

In [ ]:
df2

           Name  Age  Salary Degisnation
0  Mayank Joshi   20  165000    Engineer
1   Mamta Rawat   19  160000    Engineer
2         Peter   18   62000      Doctor
3         Linda   17   85000     Plumber

In [ ]:
df2.loc[[0,1]][['Name','Age']]

           Name  Age
0  Mayank Joshi   20
1   Mamta Rawat   19

Conditional Selection

#I want to select only whose age is above 18

In [ ]:
df2[df2['Age']>=19]

           Name  Age  Salary Degisnation
0  Mayank Joshi   20  165000    Engineer
1   Mamta Rawat   19  160000    Engineer

#I only want people whose age is above 18 and there degisnation must be AI&ML.

In [ ]:
print(df2.columns.tolist())

['Name', 'Age', 'Salary', 'Degisnation']

In [ ]:
df2.columns = df2.columns.str.strip()
print(df2.columns.tolist())

['Name', 'Age', 'Salary', 'Degisnation']

In [190]:
df2[(df2["Age"] > 18) & (df2["Job"] == "Engineer")]

           Name  Age  Salary       Job
0  Mayank Joshi   20  165000  Engineer
1   Mamta Rawat   19  160000  Engineer